# Assisted by: Gemini 2.5 Pro
openapi: 3.0.0
info:
  title: C2P Service API
  version: 0.1.0
  description: |
    API for the Compliance-to-Policy (C2P) Service. This service provides control-based attribute enrichment for telemetry data,
    leveraging internal domain logic and the C2P project's compliance knowledge.
    It's designed to be called by an OpenTelemetry Collector's custom processor to enrich logs, metrics, and traces.

#security:
#  - BearerAuth: []

paths:
  /v1/enrich:
    post:
      summary: Enrich telemetry attributes with compliance control data
      description: |
        Accepts a set of key telemetry attributes (e.g., asset ID, policy name, user ID) and
        returns additional compliance-related attributes based on internal domain logic.
        This endpoint is intended to be called by an OpenTelemetry Collector's custom processor.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EnrichmentRequest'
      responses:
        '200':
          description: Successfully enriched attributes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnrichmentResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    EnrichmentRequest:
      type: object
      properties:
        evidence:
          $ref: '#/components/schemas/RawEvidence'
      required:
        - evidence
    RawEvidence:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the raw evidence.
        class_id:
          type: integer
          description: A event class id for raw data OCSF schema
        category_id:
          type: integer
          description: A category ID for raw data OCSF schema
        timestamp:
          type: string
          format: date-time
          description: The time when the raw evidence was generated.
        source:
          type: string
          description: The source of the raw evidence (e.g., policy engine name).
        policyId:
          type: string
          description: The ID of the policy that generated the evidence.
        decision:
          type: string
          description: The decision made by the policy engine (e.g., "compliant", "non-compliant").
        rawData:
          type: string
          format: json
          description: Raw JSON output from the policy engine.
      required:
        - id
        - timestamp
        - source
        - policyId
        - decision
        - rawData

    EnrichmentResponse:
      type: object
      description: "Enriched compliance finding with risk attributes and threat mappings."
      properties:
        threats:
          type: array
          items:
            $ref: '#/components/schemas/ThreatMapping'
        compliance:
          type: array
          items:
            $ref: '#/components/schemas/Compliance'
        status:
          $ref: '#/components/schemas/Status'
      required:
        - compliance
        - status

    Status:
      type: object
      title: "Status"
      description: "Compliance Result"
      properties:
        title:
          type: string
          enum:
            - Unknown
            - Pass
            - Warning
            - Fail
            - Other
          description: "Compliance status."
        id:
          type: integer
          enum:
            - 3
            - 0
            - 1
            - 2
            - 99
          description: "Compliance status ID."
      additionalProperties: false
      required:
        - title

    Compliance:
      type: object
      title: "Compliance"
      description: "Compliance details from OCSF Security Control Profile."
      properties:
        benchmark:
          type: string
          description: "Benchmark or Security Control Catalog id"
        requirements:
          type: array
          items:
            type: string
          description: "Assessment requirements Id"
        standards:
          type: array
          items:
            type: string
          description: "List of impacted compliance standards"
      additionalProperties: false
      required:
        - requirements
        - benchmark

    ThreatMapping:
      type: object
      description: "A mapping to an external security framework, like MITRE ATT&CK."
      properties:
        referenceId:
          type: string
          description: "The name of the external reference (e.g., MITRE-ATT&CK)."
        identifiers:
          type: array
          items:
            $ref: '#/components/schemas/ThreatIdentifier'
      required:
        - referenceId
        - identifiers

    ThreatIdentifier:
      type: object
      description: "A specific threat technique or sub-technique."
      properties:
        id:
          type: string
          description: "The MITRE ID (e.g., T1059.004)."
        name:
          type: string
          description: "The name of the technique."
        url:
          type: string
          description: "The URL to the technique's page for more information."
      required:
        - id
        - name
        - url

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message

#  securitySchemes:
#    BearerAuth:
#      type: http
#      scheme: bearer
#      bearerFormat: JWT
